'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace WebDocumentMap

    Partial Public Class _Default

        '''<summary>
        '''ASPxSiteMapControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxSiteMapControl1 As Global.DevExpress.Web.ASPxSiteMapControl.ASPxSiteMapControl

        '''<summary>
        '''ASPxSiteMapDataSource1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxSiteMapDataSource1 As Global.DevExpress.Web.ASPxSiteMapControl.ASPxSiteMapDataSource

        '''<summary>
        '''ReportToolbar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportToolbar1 As Global.DevExpress.XtraReports.Web.ReportToolbar

        '''<summary>
        '''ReportViewer1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportViewer1 As Global.DevExpress.XtraReports.Web.ReportViewer
    End Class
End Namespace
